read_functions:
  - read_german_data
  - read_spect_heart
  - read_breast_cancer_data
  - read_congressional_voting_records
  - read_phishing
  - read_hr
param_grid:
  - method: [hypper_weights]
    weighting_iterations: [1, 2, 3]
    weighting_normalization_strategy: [max, l1, l2]
    feature_values: [false]
  - method: [hypper_rw]
    iterations: [10000]
    walk_length: [3]
    scoring_variant: ['v1_1', 'v1_2', 'v1_3', 'v1_4']
    feature_values: [false]
  - method: [random_forest, logistic_regression, random]
savefile: "f_selection_exp.csv"
percent_of_features: [0.3, 0.5]
feature_values: false
kfold_splits: 3
eval_algorithms:
  - LogisticRegression
  # - XGBClassifier
  - MLPClassifier
  - CatBoostClassifier
  - LGBMClassifier