read_functions:
  - read_german_data
  - read_spect_heart
  - read_banking
  - read_hr
  - read_criteo
param_grid:
  - method: [hypper]
    weighting_iteration: [1, 2, 3]
    weighting_normalization_strategy: [max, l1, l2]
    majority_left_threshold: [0.0, 0.25, 0.5]
    weighting_history: [true, false]
    version: [1, 4, 5]
    randomize_A: [0.0, 5.0, 40.0, 500.0]
  - method: [without_undersampling, tomek_links, edited_nearest_neighbours]
  - method: [random_undersampling]
    majority_left_threshold: [0.0, 0.25, 0.5]
  # - method: [near_miss]
  #   version: [1, 2]
savefile: "undersampling_exp_f.csv"
verbosity: false
kfold_splits: 6
eval_algorithms:
  # - LogisticRegression
  # - XGBClassifier
  # - MLPClassifier
  - CatBoostClassifier
  - LGBMClassifier