name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test pull request
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .['testing']

      - name: Tests
        run: |
          pytest

  upload:
    name: Upload yo PyPI
    if:  github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
        python -m pip install -e .['documentation']

    - name: Update documentation locally
      run: |
        pdoc -o docs/ -d google hypper/ --favicon https://github.com/hypper-team/hypper/raw/main/logo/favicon.png --logo https://github.com/hypper-team/hypper/raw/main/logo/logo1.png --logo-link https://hypper-team.github.io/hypper.html --footer-text "Hypper API Documentation"
        git clone https://github.com/hypper-team/hypper-team.github.io.git
        cp -r docs/* hypper-team.github.io/

    - name: Push documentation
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'hypper-team.github.io'
        destination-github-username: 'hypper-team'
        destination-repository-name: 'hypper-team.github.io'
        user-email: ${{ secrets.USER_EMAIL_GITHUB }}
        target-branch: main

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
